import{a as g,i as a,S as q}from"./assets/vendor-frHSA4Lh.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))u(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&u(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function u(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();g.defaults.baseURL="https://pixabay.com/api/";const v="50173173-c7ebe87f992e3ee35ae0a4cd8";async function h(r,t){try{const{data:s}=await g("",{params:{key:v,q:r,page:t,per_page:"15",image_type:"photo",orientation:"horizontal",safesearch:"true"}});return s}catch(s){console.log(s),a.error({title:"Error"})}}const b=document.querySelector(".gallery"),O=new q(".gallery .gallery-link",{captionsData:"alt"});function L(r){const t=r.map(({webformatURL:s,largeImageURL:u,tags:e,likes:o,views:n,comments:w,downloads:E})=>`<li class="gallery-item">
          <a class="gallery-link" href="${u}"><img class="gallery-image" src="${s}" alt="${e}" />
          <p>Likes <span>${o}</span></p>
          <p>Views <span>${n}</span></p>
          <p>Comments <span>${w}</span></p>
          <p>Downloads <span>${E}</span></p>
          </a>
        </li>`).join("");b.insertAdjacentHTML("beforeend",t),O.refresh()}function P(){b.innerHTML=""}function d(r){r.classList.remove("hidden")}function l(r){r.classList.add("hidden")}const f=document.querySelector(".form");f.querySelector('input[name="search-text]');f.querySelector("button");const p=document.querySelector(".loader"),y=document.querySelector(".loader-more"),c=document.querySelector(".load-more-btn");let i=1,S=0,m="";f.addEventListener("submit",I);c.addEventListener("click",$);async function I(r){if(r.preventDefault(),P(),m=r.target.elements["search-text"].value.trim(),i=1,m===""){a.warning({title:"Caution",message:"You forgot to type what you search"});return}d(p);try{const t=await h(m,i);if(t.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}L(t.hits),t.totalHits<=15?l(c):d(c),S=Math.ceil(t.totalHits/15)}catch(t){console.log(t),a.error({message:t.message})}finally{l(p),f.reset()}}async function $(){i+=1,d(y);try{const r=await h(m,i);L(r.hits),S<=i?(l(c),a.info({message:"We're sorry, but you've reached the end of search results."})):d(c);const s=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}catch(r){console.log(r),a.error({title:"Error",message:"Illegal operation"})}finally{l(p),l(y)}}
//# sourceMappingURL=index.js.map
