import{a as u,i,S as d}from"./assets/vendor-frHSA4Lh.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();u.defaults.baseURL="https://pixabay.com/api/";const y="50173173-c7ebe87f992e3ee35ae0a4cd8";function g(o){return u("",{params:{key:y,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true"}}).then(r=>r.data).catch(r=>{console.log(r),i.error({title:"Error"})})}const p=document.querySelector(".gallery"),h=new d(".gallery .gallery-link",{captionsData:"alt"});function L(o){const r=o.map(({webformatURL:a,largeImageURL:n,tags:e,likes:t,views:s,comments:f,downloads:m})=>`<li class="gallery-item">
          <a class="gallery-link" href="${n}"><img class="gallery-image" src="${a}" alt="${e}" />
          <p>Likes <span>${t}</span></p>
          <p>Views <span>${s}</span></p>
          <p>Comments <span>${f}</span></p>
          <p>Downloads <span>${m}</span></p>
          </a>
        </li>`).join("");p.innerHTML=r,h.refresh()}function b(){p.innerHTML=""}function S(o){o.classList.remove("hidden")}function q(o){o.classList.add("hidden")}const l=document.querySelector(".form");l.querySelector('input[name="search-text]');l.querySelector("button");const c=document.querySelector(".loader");l.addEventListener("submit",w);function w(o){o.preventDefault(),b();const r=o.target.elements["search-text"].value.trim();if(r===""){i.warning({title:"Caution",message:"You forgot to type what you search"});return}S(c),g(r).then(a=>{if(a.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}L(a.hits)}).catch(a=>{console.log(a),i.error({title:"Error",message:"Illegal operation"})}).finally(()=>{q(c),l.reset()})}
//# sourceMappingURL=index.js.map
